export const robots = [
    {
        id:1,
        name:'vaishnavi',
        username:'citrus',
        email:'citrusorange@gmail.com'
    },
    {
        id:2,
        name:'iyer',
        username:'orange',
        email:'orangecitrus@gmail.com'
    },
    {
        id:4,
        name:'vaishnavi',
        username:'citrus',
        email:'citrusorange@gmail.com'
    },
    {
        id:5,
        name:'iyer',
        username:'orange',
        email:'orangecitrus@gmail.com'
    },
    {
        id:3,
        name:'kanaga',
        username:'care',
        email:'careor@gmail.com'
    },
    {
        id:6,
        name:'kanaga',
        username:'care',
        email:'careor@gmail.com'
    }
]